@startuml Login to the system (Post)

header co-working Space 
footer Page %page% of %lastpage%
title "Login (Post)"

participant "Client" as client
participant "<<javaScript>>\n:server" as server
participant "<<router>>\n:auths" as routerAuth
participant "<<controllers>>\n:auth" as controllersAuths
' participant "<<middleware>>\n:auth" as middleware
participant "<<model>>\n:User" as modelUser
database "<<MongoDB>>\n:users" as UserDatabase

client->server ++:req.post('/login')
server->routerAuth ++:app.use('/login',auth)
routerAuth -> controllersAuths ++:login(email, password)
controllersAuths -> modelUser ++: login(email, password)
' controllersAuths -> UserDatabase ++: validate email
' UserDatabase -> controllersAuths ++: return validation result
modelUser -->  UserDatabase ++:login(email, password)
UserDatabase --> modelUser --:response
modelUser --> controllersAuths --:response
controllersAuths --> client --:response

@enduml
