@startuml Get one Reservation (GET)

header Sameple Co-working space Sequence Diagram
footer Page %page% of %lastpage%
title "Get one Reservation (GET)"

participant "Client" as client
participant "<<javaScript>>\n:server" as server
participant "<<router>>\n:reservations" as routerReservation
participant "<<middleware>>\n:auth" as middleware
participant "<<controllers>>\n:reservations" as controllersReservation
participant "<<model>>\n:Reservation" as modelReservation
database "<<MongoDB>>\n:reservations" as ReservationDatabase

client->server ++:req.get('/reservations/:id')
server->routerReservation ++:app.use('/reservations/:id',reservation)
routerReservation -> middleware ++: protect
middleware -> routerReservation --: 
routerReservation -> controllersReservation ++:getReservationById(id)
controllersReservation->modelReservation ++:getReservationById(id)
modelReservation ->ReservationDatabase ++: findById(id)
ReservationDatabase --> modelReservation --: reservation #id
controllersReservation <-- modelReservation --: reservation #id
controllersReservation->client --:response

@enduml
