@startuml Update Hospital (PUT)

header Sameple VacQ Sequence Diagram
footer Page %page% of %lastpage%
title "Update Hospital (PUT)"

participant "Client" as client
participant "<<javaScript>>\n:server" as server
participant "<<router>>\n:reservations" as routerReservation
participant "<<controllers>>\n:reservations" as controllersReservation
participant "<<model>>\n:Reservation" as modelReservation
database "<<MongoDB>>\n:reservations" as ReservationDatabase

client->server ++:req.put('/reservations/:id')
server->routerReservation ++:app.use('/reservations/:id',reservation)
routerReservation -> middleware ++: protect
middleware -> routerReservation --: 
routerReservation -> controllersReservation ++:updateReservation(id)
controllersReservation->modelReservation ++:updateReservation(id)
modelReservation ->ReservationDatabase ++: findByIdAndUpdate(id)
ReservationDatabase --> modelReservation --: reservation
controllersReservation <-- modelReservation --: reservation
controllersReservation->client --:response

@enduml
