@startuml Get All Hospitals (GET)

header Sameple VacQ Sequence Diagram
footer Page %page% of %lastpage%
title "Get All Hospitals (GET)"

participant "Client" as client
participant "<<javaScript>>\n:server" as server
participant "<<router>>\n:reservations" as routerReservation
participant "<<controllers>>\n:reservations" as controllersReservation
participant "<<model>>\n:Reservation" as modelReservation
database "<<MongoDB>>\n:reservations" as ReservationDatabase

client->server ++:req.get('/reservations')
server->routerReservation ++:app.use('/reservations',reservation)
routerReservation -> controllersReservation ++:getHospitals()
controllersReservation->modelReservation ++:getHospitals()
modelReservation ->ReservationDatabase ++: ReservationSchema
ReservationDatabase --> modelReservation --: list of reservations owned by user
controllersReservation <-- modelReservation --:list of reservations owned by user
controllersReservation->client --:response

@enduml
